apiVersion: theme.halo.run/v1alpha1
kind: Theme
metadata:
  name: halo-theme-wind
spec:
  displayName: Wind
  author:
    name: Ricky Gu
    website: https://www.gurenkai.com
  description: 一个简约的突出内容的主题
  logo: https://halo.run/logo
  website: https://github.com/halo-sigs/theme-foo
  repo: https://github.com/halo-sigs/theme-foo.git
  settingName: "halo-theme-wind-setting"
  configMapName: "halo-theme-wind-configMap"
  customTemplates:
    post:
      - name: 文档
        description: 文档类型的文章
        screenshot: 
        file: post_documentation.html
    category:
      - name: 知识库
        description: 知识库类型的分类
        screenshot: 
        file: category_knowledge.html
    page:
      - name: 关于
        description: 关于页面
        screenshot:
        file: page_about.html
  version: 1.0.0
  require: 2.0.0